# Generated by Django 4.2 on 2023-04-26 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateField(default=datetime.date(2023, 4, 26)),
        ),
    ]
